-- 單位通行碼登入的暴力破解防護。
--
-- Artifact 有這個機制（PIN_MAX=5、PIN_MS=30 分鐘，見 reibi-v10 的 checkLk/failPin/clearLk），
-- 且 SetupWizard 畫面對使用者明白承諾「管理者PIN錯誤5次鎖定30分鐘」。移植時漏掉了，
-- 於是四條登入路徑中防護最弱的那條反而完全沒有節流：單位通行碼是全組織共用、
-- 猜中一次即可讀取整間企業的健康資料，而 Supabase Auth 那條（reibi_internal_login_audit）
-- 早就有 10 分鐘 5 次的限制。
--
-- 不重用 reibi_internal_login_audit：該表的 email_hash 與 auth_user_id 外鍵都綁定個人帳號，
-- 單位通行碼沒有 email 也沒有 auth 使用者，塞進去會讓欄位語意錯亂。
--
-- 與既有稽核表一致，這裡同樣只存 HMAC 指紋，不存單位代碼明文、不存原始 IP。

create table public.reibi_org_login_attempts (
  id bigint generated by default as identity primary key,
  -- HMAC(jwt_secret, org_code)；金鑰輪替會讓舊指紋失效，對節流而言只是計數歸零，可接受。
  org_hash text not null,
  -- 角色為 member/dept_head/admin/occupational_health 四個固定值，不具識別性，存明文便於維運。
  role text not null,
  ip_hash text,
  succeeded boolean not null,
  created_at timestamptz not null default now()
);

comment on table public.reibi_org_login_attempts is
  'Org passcode login throttling. Stores HMAC fingerprints only: no plaintext org code, no raw IP.';

-- 第一層：同一 IP 對同一單位角色的失敗次數。
create index reibi_org_login_attempts_ip_idx
  on public.reibi_org_login_attempts (org_hash, role, ip_hash, created_at desc)
  where not succeeded;

-- 第二層：跨 IP 的單位層失敗次數，用來擋分散式嘗試。
create index reibi_org_login_attempts_org_idx
  on public.reibi_org_login_attempts (org_hash, role, created_at desc)
  where not succeeded;

-- 供清理舊資料使用。
create index reibi_org_login_attempts_cleanup_idx
  on public.reibi_org_login_attempts (created_at);

alter table public.reibi_org_login_attempts enable row level security;
revoke all on public.reibi_org_login_attempts from anon, authenticated;
grant all on public.reibi_org_login_attempts to service_role;
