-- Extend the baseline sleep platform with the REIBI business and health domain.
-- Browser roles intentionally receive no direct Data API privileges. FastAPI
-- accesses these tables with service_role and remains the authorization layer.

create table public.reibi_enterprises (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  org_code text not null unique,
  org_name text not null,
  org_alias text,
  enterprise_type text not null default 'enterprise'
    check (enterprise_type in ('enterprise', 'partner')),
  status text not null default 'pending',
  ubn text,
  contact_name text,
  phone text,
  email text,
  address text,
  industry text,
  plan_code text,
  member_limit integer not null default 0 check (member_limit >= 0),
  used_count integer not null default 0 check (used_count >= 0),
  contract_start date,
  contract_end date,
  contract_years smallint check (contract_years is null or contract_years > 0),
  pay_mode text,
  consultant text,
  partner_code text,
  referral_percent numeric(5,2)
    check (referral_percent is null or referral_percent between 0 and 100),
  a_layer_fee numeric(14,2) not null default 0 check (a_layer_fee >= 0),
  b_layer_fee numeric(14,2) not null default 0 check (b_layer_fee >= 0),
  c_layer_fee numeric(14,2) not null default 0 check (c_layer_fee >= 0),
  d_layer_fee numeric(14,2) not null default 0 check (d_layer_fee >= 0),
  devices jsonb not null default '{}'::jsonb,
  d_layer_config jsonb not null default '{}'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (contract_end is null or contract_start is null or contract_end >= contract_start)
);

create unique index reibi_enterprises_ubn_uidx
  on public.reibi_enterprises (ubn) where ubn is not null and ubn <> '';
create index reibi_enterprises_status_idx
  on public.reibi_enterprises (status, contract_end);

create table public.reibi_enterprise_sites (
  id bigint generated by default as identity primary key,
  enterprise_id bigint not null references public.reibi_enterprises(id) on delete cascade,
  artifact_id text,
  label text not null,
  address text,
  note text,
  sort_order integer not null default 0 check (sort_order >= 0),
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (enterprise_id, artifact_id)
);
create index reibi_enterprise_sites_enterprise_id_idx
  on public.reibi_enterprise_sites (enterprise_id);

create table public.reibi_departments (
  id bigint generated by default as identity primary key,
  enterprise_id bigint not null references public.reibi_enterprises(id) on delete cascade,
  parent_id bigint references public.reibi_departments(id) on delete cascade,
  artifact_key text,
  name text not null,
  hierarchy_level smallint not null default 1 check (hierarchy_level between 1 and 4),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (enterprise_id, artifact_key)
);
create index reibi_departments_enterprise_id_idx on public.reibi_departments (enterprise_id);
create index reibi_departments_parent_id_idx on public.reibi_departments (parent_id);

create table public.reibi_staff (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  employee_code text unique,
  name text not null,
  title text,
  phone text,
  email text,
  note text,
  is_active boolean not null default true,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reibi_distributors (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  parent_id bigint references public.reibi_distributors(id) on delete set null,
  staff_id bigint references public.reibi_staff(id) on delete set null,
  org_code text not null unique,
  distributor_type text not null check (distributor_type in ('primary', 'sub')),
  name text not null,
  alias text,
  status text not null default 'active',
  region text,
  level_code text,
  ubn text,
  address text,
  contact_name text,
  phone text,
  email text,
  has_sub_authority boolean not null default false,
  commission_percent numeric(5,2)
    check (commission_percent is null or commission_percent between 0 and 100),
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index reibi_distributors_parent_id_idx on public.reibi_distributors (parent_id);
create index reibi_distributors_staff_id_idx on public.reibi_distributors (staff_id);
create index reibi_distributors_status_idx on public.reibi_distributors (status, distributor_type);

create table public.reibi_partners (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  name text not null,
  contact_name text,
  phone text,
  default_percent numeric(5,2) not null default 0 check (default_percent between 0 and 100),
  note text,
  is_active boolean not null default true,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reibi_quotes (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  doc_no text not null unique,
  doc_type text not null,
  status text not null,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  distributor_id bigint references public.reibi_distributors(id) on delete set null,
  partner_id bigint references public.reibi_partners(id) on delete set null,
  staff_id bigint references public.reibi_staff(id) on delete set null,
  client_name text not null,
  client_alias text,
  contact_name text,
  phone text,
  email text,
  address text,
  industry text,
  member_count integer check (member_count is null or member_count >= 0),
  pay_mode text,
  contract_years smallint check (contract_years is null or contract_years > 0),
  contract_start date,
  contract_end date,
  a_layer_fee numeric(14,2) not null default 0 check (a_layer_fee >= 0),
  b_layer_fee numeric(14,2) not null default 0 check (b_layer_fee >= 0),
  c_layer_fee numeric(14,2) not null default 0 check (c_layer_fee >= 0),
  d_layer_fee_min numeric(14,2) not null default 0 check (d_layer_fee_min >= 0),
  d_layer_fee_max numeric(14,2) not null default 0 check (d_layer_fee_max >= 0),
  e_layer_fee numeric(14,2) not null default 0 check (e_layer_fee >= 0),
  total_year_fee numeric(14,2) not null default 0 check (total_year_fee >= 0),
  total_contract_fee numeric(14,2) not null default 0 check (total_contract_fee >= 0),
  original_contract_no text,
  linked_contract_no text,
  config jsonb not null default '{}'::jsonb,
  versions jsonb not null default '[]'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (contract_end is null or contract_start is null or contract_end >= contract_start)
);
create index reibi_quotes_enterprise_id_idx on public.reibi_quotes (enterprise_id);
create index reibi_quotes_distributor_id_idx on public.reibi_quotes (distributor_id);
create index reibi_quotes_partner_id_idx on public.reibi_quotes (partner_id);
create index reibi_quotes_staff_id_idx on public.reibi_quotes (staff_id);
create index reibi_quotes_status_idx on public.reibi_quotes (status, created_at desc);

create table public.reibi_contracts (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  doc_no text not null unique,
  contract_type text not null,
  status text not null,
  quote_id bigint references public.reibi_quotes(id) on delete set null,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  from_quote_no text,
  client_name text not null,
  contract_start date,
  contract_end date,
  total_year_fee numeric(14,2) not null default 0 check (total_year_fee >= 0),
  total_contract_fee numeric(14,2) not null default 0 check (total_contract_fee >= 0),
  terms jsonb not null default '{}'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (contract_end is null or contract_start is null or contract_end >= contract_start)
);
create index reibi_contracts_quote_id_idx on public.reibi_contracts (quote_id);
create index reibi_contracts_enterprise_id_idx on public.reibi_contracts (enterprise_id);
create index reibi_contracts_status_idx on public.reibi_contracts (status, contract_end);

create table public.reibi_work_orders (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  work_order_no text not null unique,
  contract_id bigint references public.reibi_contracts(id) on delete set null,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  service_staff_id bigint references public.reibi_staff(id) on delete set null,
  contract_no text,
  client_name text not null,
  status text not null,
  contact_name text,
  phone text,
  email text,
  address text,
  scheduled_date date,
  service_period text,
  staff_names text,
  scope_confirm_reibi text,
  scope_confirm_reibi_date date,
  scope_confirm_client text,
  scope_confirm_client_date date,
  acceptance_result text,
  acceptance_date date,
  client_sign_name text,
  punch_list text,
  items jsonb not null default '{}'::jsonb,
  acceptance jsonb not null default '{}'::jsonb,
  status_history jsonb not null default '[]'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index reibi_work_orders_contract_id_idx on public.reibi_work_orders (contract_id);
create index reibi_work_orders_enterprise_id_idx on public.reibi_work_orders (enterprise_id);
create index reibi_work_orders_service_staff_id_idx on public.reibi_work_orders (service_staff_id);
create index reibi_work_orders_status_idx on public.reibi_work_orders (status, scheduled_date);

create table public.reibi_invoices (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  invoice_no text not null unique,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  org_code text,
  org_name text,
  ubn text,
  invoice_date date not null,
  layer_code text,
  status text not null,
  tax_exclusive numeric(14,2) not null default 0 check (tax_exclusive >= 0),
  tax numeric(14,2) not null default 0 check (tax >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  notes text,
  linked_remittance_id bigint,
  items jsonb not null default '[]'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index reibi_invoices_enterprise_id_idx on public.reibi_invoices (enterprise_id);
create index reibi_invoices_status_idx on public.reibi_invoices (status, invoice_date desc);

create table public.reibi_remittances (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  org_code text,
  org_name_guess text,
  corrected_name text,
  corrected_account text,
  remitted_on date,
  amount numeric(14,2) not null default 0 check (amount >= 0),
  status text not null default 'pending',
  note text,
  ai_result jsonb,
  ai_provider text check (ai_provider is null or ai_provider = 'gemini'),
  ai_model text,
  image_storage_path text,
  review_payload jsonb not null default '{}'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index reibi_remittances_enterprise_id_idx on public.reibi_remittances (enterprise_id);
create index reibi_remittances_status_idx on public.reibi_remittances (status, submitted_at desc);

alter table public.reibi_invoices
  add constraint reibi_invoices_linked_remittance_id_fkey
  foreign key (linked_remittance_id) references public.reibi_remittances(id) on delete set null;
create index reibi_invoices_linked_remittance_id_idx
  on public.reibi_invoices (linked_remittance_id);

create table public.reibi_subscriptions (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  member_code text not null,
  subscriber_name text,
  contact text,
  plan_code text not null,
  plan_label text,
  status text not null,
  amount numeric(14,2) not null default 0 check (amount >= 0),
  invoice_no text,
  activation_code text,
  consent_version text,
  consent_at timestamptz,
  requested_at timestamptz,
  approved_at timestamptz,
  expires_at timestamptz,
  admin_note text,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_code, requested_at)
);
create index reibi_subscriptions_member_status_idx
  on public.reibi_subscriptions (member_code, status, expires_at desc);

create table public.reibi_service_tickets (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  ticket_type text not null,
  priority text not null,
  status text not null,
  preferred_date date,
  note text,
  handler text,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index reibi_service_tickets_enterprise_id_idx on public.reibi_service_tickets (enterprise_id);
create index reibi_service_tickets_queue_idx
  on public.reibi_service_tickets (status, priority, created_at);

create table public.reibi_message_logs (
  id bigint generated by default as identity primary key,
  artifact_id text unique,
  target_type text not null,
  target_artifact_id text,
  target_name text,
  template_code text,
  message text not null,
  sender text,
  status text not null,
  source_payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default now()
);
create index reibi_message_logs_target_idx
  on public.reibi_message_logs (target_type, target_artifact_id, sent_at desc);

create table public.reibi_health_assessments (
  id bigint generated by default as identity primary key,
  artifact_id text,
  profile_id uuid references public.profiles(id) on delete set null,
  artifact_user_key text,
  org_code text,
  assessment_type text not null
    check (assessment_type in ('combined', 'sleep', 'pain', 'work', 'ow', 'msk', 'bsrs5', 'violence', 'mental')),
  score numeric(8,2),
  secondary_score numeric(8,2),
  level_code text,
  level_label text,
  is_flagged boolean not null default false,
  answers jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '{}'::jsonb,
  ai_provider text check (ai_provider is null or ai_provider = 'gemini'),
  ai_model text,
  source_payload jsonb not null default '{}'::jsonb,
  assessed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (assessment_type, artifact_user_key, artifact_id)
);
create index reibi_health_assessments_profile_id_idx on public.reibi_health_assessments (profile_id);
create index reibi_health_assessments_org_type_idx
  on public.reibi_health_assessments (org_code, assessment_type, assessed_at desc);
create index reibi_health_assessments_user_type_idx
  on public.reibi_health_assessments (artifact_user_key, assessment_type, assessed_at desc);

create table public.reibi_health_diary_entries (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  artifact_user_key text,
  diary_type text not null check (diary_type in ('sleep', 'pain')),
  entry_date date not null,
  source_payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (artifact_user_key, diary_type, entry_date)
);
create index reibi_health_diary_entries_profile_id_idx on public.reibi_health_diary_entries (profile_id);
create index reibi_health_diary_entries_user_idx
  on public.reibi_health_diary_entries (artifact_user_key, diary_type, entry_date desc);

create table public.reibi_ohs_records (
  id bigint generated by default as identity primary key,
  artifact_id text,
  enterprise_id bigint references public.reibi_enterprises(id) on delete cascade,
  org_code text not null,
  record_type text not null check (record_type in ('hazard', 'measure', 'review', 'meta', 'roster')),
  status text,
  risk_level text,
  owner text,
  due_date date,
  verified_at date,
  source_payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_code, record_type, artifact_id)
);
create index reibi_ohs_records_enterprise_id_idx on public.reibi_ohs_records (enterprise_id);
create index reibi_ohs_records_org_type_idx
  on public.reibi_ohs_records (org_code, record_type, status);

create table public.reibi_org_aggregates (
  id bigint generated by default as identity primary key,
  org_code text not null,
  department_key text not null default '',
  aggregate_type text not null,
  sample_size integer not null check (sample_size >= 5),
  metrics jsonb not null,
  period_start date,
  period_end date,
  calculated_at timestamptz not null default now(),
  source_payload jsonb not null default '{}'::jsonb,
  unique (org_code, department_key, aggregate_type, calculated_at)
);
create index reibi_org_aggregates_lookup_idx
  on public.reibi_org_aggregates (org_code, aggregate_type, calculated_at desc);

create table public.reibi_artifact_import_batches (
  id bigint generated by default as identity primary key,
  source_artifact text not null
    check (source_artifact in ('main', 'l5', 'quote', 'workorder')),
  source_version text,
  export_sha256 text,
  status text not null default 'pending'
    check (status in ('pending', 'validating', 'importing', 'completed', 'failed')),
  record_count integer not null default 0 check (record_count >= 0),
  imported_count integer not null default 0 check (imported_count >= 0),
  rejected_count integer not null default 0 check (rejected_count >= 0),
  error_summary jsonb not null default '[]'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create index reibi_artifact_import_batches_created_by_idx
  on public.reibi_artifact_import_batches (created_by);
create index reibi_artifact_import_batches_status_idx
  on public.reibi_artifact_import_batches (status, created_at desc);

create table public.reibi_artifact_import_records (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.reibi_artifact_import_batches(id) on delete cascade,
  storage_key text not null,
  source_record_id text not null default '',
  target_table text,
  target_id text,
  status text not null default 'pending'
    check (status in ('pending', 'imported', 'skipped', 'rejected')),
  error_detail text,
  raw_payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (batch_id, storage_key, source_record_id)
);
create index reibi_artifact_import_records_batch_id_idx
  on public.reibi_artifact_import_records (batch_id);
create index reibi_artifact_import_records_status_idx
  on public.reibi_artifact_import_records (batch_id, status);

-- RLS is also enabled by the existing event trigger, but explicit declarations
-- make the security boundary visible and keep the migration portable.
alter table public.reibi_enterprises enable row level security;
alter table public.reibi_enterprise_sites enable row level security;
alter table public.reibi_departments enable row level security;
alter table public.reibi_staff enable row level security;
alter table public.reibi_distributors enable row level security;
alter table public.reibi_partners enable row level security;
alter table public.reibi_quotes enable row level security;
alter table public.reibi_contracts enable row level security;
alter table public.reibi_work_orders enable row level security;
alter table public.reibi_invoices enable row level security;
alter table public.reibi_remittances enable row level security;
alter table public.reibi_subscriptions enable row level security;
alter table public.reibi_service_tickets enable row level security;
alter table public.reibi_message_logs enable row level security;
alter table public.reibi_health_assessments enable row level security;
alter table public.reibi_health_diary_entries enable row level security;
alter table public.reibi_ohs_records enable row level security;
alter table public.reibi_org_aggregates enable row level security;
alter table public.reibi_artifact_import_batches enable row level security;
alter table public.reibi_artifact_import_records enable row level security;

revoke all privileges on table
  public.reibi_enterprises,
  public.reibi_enterprise_sites,
  public.reibi_departments,
  public.reibi_staff,
  public.reibi_distributors,
  public.reibi_partners,
  public.reibi_quotes,
  public.reibi_contracts,
  public.reibi_work_orders,
  public.reibi_invoices,
  public.reibi_remittances,
  public.reibi_subscriptions,
  public.reibi_service_tickets,
  public.reibi_message_logs,
  public.reibi_health_assessments,
  public.reibi_health_diary_entries,
  public.reibi_ohs_records,
  public.reibi_org_aggregates,
  public.reibi_artifact_import_batches,
  public.reibi_artifact_import_records
from public, anon, authenticated;

grant all privileges on table
  public.reibi_enterprises,
  public.reibi_enterprise_sites,
  public.reibi_departments,
  public.reibi_staff,
  public.reibi_distributors,
  public.reibi_partners,
  public.reibi_quotes,
  public.reibi_contracts,
  public.reibi_work_orders,
  public.reibi_invoices,
  public.reibi_remittances,
  public.reibi_subscriptions,
  public.reibi_service_tickets,
  public.reibi_message_logs,
  public.reibi_health_assessments,
  public.reibi_health_diary_entries,
  public.reibi_ohs_records,
  public.reibi_org_aggregates,
  public.reibi_artifact_import_batches,
  public.reibi_artifact_import_records
to service_role;

revoke all privileges on all sequences in schema public from public, anon, authenticated;
grant usage, select on all sequences in schema public to service_role;
