-- REIBI Batch C: finance, partners, staff, distributors and commission ledger.
-- The browser roles intentionally receive no privileges. FastAPI accesses these
-- tables with the server-side service_role after enforcing application scopes.

create table public.reibi_finance_settings (
  id smallint primary key default 1 check (id = 1),
  min_reibi_retain_percent numeric(5,2) not null default 65
    check (min_reibi_retain_percent between 0 and 100),
  updated_by text,
  updated_at timestamptz not null default now()
);

insert into public.reibi_finance_settings (id, min_reibi_retain_percent)
values (1, 65)
on conflict (id) do nothing;

alter table public.reibi_distributors
  add column commission_a_percent numeric(5,2)
    check (commission_a_percent is null or commission_a_percent between 0 and 100),
  add column commission_b_percent numeric(5,2)
    check (commission_b_percent is null or commission_b_percent between 0 and 100),
  add column commission_c_percent numeric(5,2)
    check (commission_c_percent is null or commission_c_percent between 0 and 100),
  add column sub_contract_start date,
  add column sub_commission_a_percent numeric(5,2)
    check (sub_commission_a_percent is null or sub_commission_a_percent between 0 and 100),
  add column sub_commission_b_percent numeric(5,2)
    check (sub_commission_b_percent is null or sub_commission_b_percent between 0 and 100),
  add column sub_commission_c_percent numeric(5,2)
    check (sub_commission_c_percent is null or sub_commission_c_percent between 0 and 100),
  add column note text;

create table public.reibi_payment_schedules (
  id bigint generated by default as identity primary key,
  enterprise_id bigint not null references public.reibi_enterprises(id) on delete cascade,
  contract_id bigint references public.reibi_contracts(id) on delete set null,
  installment_code text not null,
  layer_code text not null check (layer_code in ('A', 'B', 'C', 'D')),
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  due_date date,
  status text not null default '待付款'
    check (status in ('待付款', '未到期', '待確認', '部分付款', '已付款')),
  paid_amount numeric(14,2) not null default 0 check (paid_amount >= 0),
  paid_at timestamptz,
  notified_at date,
  linked_remittance_id bigint references public.reibi_remittances(id) on delete set null,
  source_payload jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (enterprise_id, installment_code),
  check (paid_amount <= amount)
);
create index reibi_payment_schedules_enterprise_due_idx
  on public.reibi_payment_schedules (enterprise_id, due_date, status);
create index reibi_payment_schedules_open_idx
  on public.reibi_payment_schedules (due_date, enterprise_id)
  where status not in ('已付款', '未到期', '待確認');
create index reibi_payment_schedules_remittance_idx
  on public.reibi_payment_schedules (linked_remittance_id)
  where linked_remittance_id is not null;

create table public.reibi_remittance_allocations (
  id bigint generated by default as identity primary key,
  remittance_id bigint not null references public.reibi_remittances(id) on delete cascade,
  payment_schedule_id bigint not null references public.reibi_payment_schedules(id) on delete restrict,
  allocated_amount numeric(14,2) not null check (allocated_amount > 0),
  reviewed_by text,
  reviewed_at timestamptz not null default now(),
  note text,
  unique (remittance_id, payment_schedule_id)
);
create index reibi_remittance_allocations_schedule_idx
  on public.reibi_remittance_allocations (payment_schedule_id);

create or replace function public.reibi_reconcile_remittance(
  p_remittance_id bigint,
  p_schedule_ids bigint[],
  p_amount numeric,
  p_reviewed_by text,
  p_note text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_remittance public.reibi_remittances%rowtype;
  v_schedule public.reibi_payment_schedules%rowtype;
  v_remaining numeric(14,2);
  v_allocate numeric(14,2);
  v_total_due numeric(14,2) := 0;
  v_selected_count integer := 0;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception '沖帳金額必須大於 0';
  end if;
  if coalesce(array_length(p_schedule_ids, 1), 0) = 0 then
    raise exception '至少選擇一筆應收項目';
  end if;

  select * into v_remittance
  from public.reibi_remittances
  where id = p_remittance_id
  for update;
  if not found then raise exception '找不到匯款申報'; end if;
  if v_remittance.status not in ('pending', '待審核', '金額不符') then
    raise exception '此匯款申報目前不可沖帳';
  end if;

  v_remaining := p_amount;
  for v_schedule in
    select * from public.reibi_payment_schedules
    where id = any(p_schedule_ids)
    order by due_date nulls last, id
    for update
  loop
    if v_schedule.enterprise_id is distinct from v_remittance.enterprise_id then
      raise exception '匯款與應收項目不屬於同一企業';
    end if;
    if v_schedule.status = '已付款' then continue; end if;
    v_selected_count := v_selected_count + 1;
    v_total_due := v_total_due + (v_schedule.amount - v_schedule.paid_amount);
    v_allocate := least(v_remaining, v_schedule.amount - v_schedule.paid_amount);
    if v_allocate > 0 then
      insert into public.reibi_remittance_allocations (
        remittance_id, payment_schedule_id, allocated_amount, reviewed_by, note
      ) values (
        p_remittance_id, v_schedule.id, v_allocate, p_reviewed_by, p_note
      )
      on conflict (remittance_id, payment_schedule_id) do update
      set allocated_amount = excluded.allocated_amount,
          reviewed_by = excluded.reviewed_by,
          reviewed_at = now(),
          note = excluded.note;

      update public.reibi_payment_schedules
      set paid_amount = paid_amount + v_allocate,
          status = case when paid_amount + v_allocate >= amount then '已付款' else '部分付款' end,
          paid_at = case when paid_amount + v_allocate >= amount then now() else paid_at end,
          linked_remittance_id = p_remittance_id,
          updated_at = now()
      where id = v_schedule.id;
      v_remaining := v_remaining - v_allocate;
    end if;
    exit when v_remaining <= 0;
  end loop;

  if v_selected_count = 0 then raise exception '找不到可沖帳的應收項目'; end if;

  update public.reibi_remittances
  set status = case when p_amount = v_total_due then '已沖帳' else '金額不符' end,
      review_payload = jsonb_build_object(
        'schedule_ids', p_schedule_ids,
        'claimed_amount', p_amount,
        'total_due_amount', v_total_due,
        'diff_amount', p_amount - v_total_due,
        'reviewed_by', p_reviewed_by,
        'note', p_note
      ),
      reviewed_at = now(),
      updated_at = now()
  where id = p_remittance_id;

  return jsonb_build_object(
    'status', case when p_amount = v_total_due then '已沖帳' else '金額不符' end,
    'claimed_amount', p_amount,
    'total_due_amount', v_total_due,
    'diff_amount', p_amount - v_total_due,
    'remaining_amount', v_remaining
  );
end;
$$;

create table public.reibi_commission_ledger (
  id bigint generated by default as identity primary key,
  distributor_id bigint not null references public.reibi_distributors(id) on delete restrict,
  period_month date not null check (period_month = date_trunc('month', period_month)::date),
  a_base numeric(14,2) not null default 0 check (a_base >= 0),
  b_base numeric(14,2) not null default 0 check (b_base >= 0),
  c_base numeric(14,2) not null default 0 check (c_base >= 0),
  a_percent numeric(5,2) not null check (a_percent between 0 and 100),
  b_percent numeric(5,2) not null check (b_percent between 0 and 100),
  c_percent numeric(5,2) not null check (c_percent between 0 and 100),
  a_commission numeric(14,2) not null default 0 check (a_commission >= 0),
  b_commission numeric(14,2) not null default 0 check (b_commission >= 0),
  c_commission numeric(14,2) not null default 0 check (c_commission >= 0),
  total_commission numeric(14,2) not null default 0 check (total_commission >= 0),
  status text not null default '已確認待匯款'
    check (status in ('已確認待匯款', '已匯款')),
  note text,
  calculation_snapshot jsonb not null default '{}'::jsonb,
  confirmed_by text not null,
  confirmed_at timestamptz not null default now(),
  paid_by text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  unique (distributor_id, period_month)
);
create index reibi_commission_ledger_period_status_idx
  on public.reibi_commission_ledger (period_month desc, status, distributor_id);

alter table public.reibi_invoices
  add column subscription_id bigint references public.reibi_subscriptions(id) on delete set null;
create index reibi_invoices_subscription_id_idx
  on public.reibi_invoices (subscription_id)
  where subscription_id is not null;

alter table public.reibi_subscriptions
  add column activation_code_hash text,
  add column activation_code_last_four text,
  add column activation_code_issued_at timestamptz,
  add column activation_code_issued_by text;

-- Keep any pre-existing value intact until the Artifact-data migration preflight
-- has produced an explicit rotation report. New FastAPI writes always leave the
-- legacy activation_code column null and store only the digest/last four digits.

alter table public.reibi_finance_settings enable row level security;
alter table public.reibi_payment_schedules enable row level security;
alter table public.reibi_remittance_allocations enable row level security;
alter table public.reibi_commission_ledger enable row level security;

revoke all privileges on table
  public.reibi_finance_settings,
  public.reibi_payment_schedules,
  public.reibi_remittance_allocations,
  public.reibi_commission_ledger
from public, anon, authenticated;

grant all privileges on table
  public.reibi_finance_settings,
  public.reibi_payment_schedules,
  public.reibi_remittance_allocations,
  public.reibi_commission_ledger
to service_role;

revoke all on function public.reibi_reconcile_remittance(bigint, bigint[], numeric, text, text)
  from public, anon, authenticated;
grant execute on function public.reibi_reconcile_remittance(bigint, bigint[], numeric, text, text)
  to service_role;

revoke all privileges on all sequences in schema public from public, anon, authenticated;
grant usage, select on all sequences in schema public to service_role;
