-- Batch F: organization service center, announcements, integration queue,
-- credential-recovery workflow, department imports, and Gemini remittance OCR.
-- All browser-facing roles remain denied; FastAPI is the sole Data API client.

alter table public.appointments
  add column service_site_id bigint references public.reibi_enterprise_sites(id) on delete set null,
  add column note text;

create index appointments_service_site_id_idx
  on public.appointments (service_site_id)
  where service_site_id is not null;

alter table public.reibi_remittances
  add column receipt_mime_type text,
  add column receipt_sha256 text,
  add column ocr_status text not null default 'not_requested',
  add column ocr_confidence numeric(5,4),
  add column ocr_fields jsonb not null default '{}'::jsonb,
  add column ocr_analyzed_at timestamptz,
  add constraint reibi_remittances_ocr_status_check
    check (ocr_status in ('not_requested', 'processing', 'completed', 'needs_review', 'failed')),
  add constraint reibi_remittances_ocr_confidence_check
    check (ocr_confidence is null or (ocr_confidence >= 0 and ocr_confidence <= 1));

alter table public.reibi_service_tickets
  add column requester_profile_id uuid references public.profiles(id) on delete set null,
  add column requester_org_code text,
  add column contact_email text,
  add column response_note text,
  add column status_history jsonb not null default '[]'::jsonb,
  add column closed_at timestamptz;

create index reibi_service_tickets_requester_idx
  on public.reibi_service_tickets (requester_profile_id, created_at desc)
  where requester_profile_id is not null;

alter table public.reibi_message_logs
  alter column sent_at drop not null,
  alter column sent_at drop default,
  add column provider text not null default 'line',
  add column delivery_mode text not null default 'manual',
  add column request_key text,
  add column queued_at timestamptz,
  add column delivered_at timestamptz,
  add column failed_at timestamptz,
  add column error_message text,
  add column updated_at timestamptz not null default now(),
  add constraint reibi_message_logs_delivery_mode_check
    check (delivery_mode in ('manual', 'provider_api'));

create unique index reibi_message_logs_request_key_uidx
  on public.reibi_message_logs (request_key)
  where request_key is not null;

create index reibi_message_logs_queue_idx
  on public.reibi_message_logs (status, queued_at, id);

create table public.reibi_announcements (
  id bigint generated by default as identity primary key,
  enterprise_id bigint not null references public.reibi_enterprises(id) on delete cascade,
  template_code text,
  title text not null,
  body text not null,
  event_date date,
  quota integer check (quota is null or quota >= 0),
  status text not null default 'draft'
    check (status in ('draft', 'published', 'closed')),
  published_at timestamptz,
  created_by text,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index reibi_announcements_enterprise_status_idx
  on public.reibi_announcements (enterprise_id, status, event_date, created_at desc);

create table public.reibi_announcement_registrations (
  id bigint generated by default as identity primary key,
  announcement_id bigint not null references public.reibi_announcements(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'registered'
    check (status in ('registered', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (announcement_id, profile_id)
);

create index reibi_announcement_registrations_profile_idx
  on public.reibi_announcement_registrations (profile_id, created_at desc);

create table public.reibi_access_requests (
  id bigint generated by default as identity primary key,
  enterprise_id bigint references public.reibi_enterprises(id) on delete set null,
  org_code text,
  requester_profile_id uuid references public.profiles(id) on delete set null,
  requester_name text not null,
  requester_email text not null,
  request_type text not null
    check (request_type in ('credential_recovery', 'permission_change', 'pin_retirement')),
  requested_role text,
  reason text not null,
  status text not null default 'pending'
    check (status in ('pending', 'verified', 'approved', 'rejected', 'completed')),
  verification_method text,
  resolution_note text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index reibi_access_requests_queue_idx
  on public.reibi_access_requests (status, created_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'reibi-remittance-receipts',
  'reibi-remittance-receipts',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.reibi_replace_departments(
  p_enterprise_id bigint,
  p_rows jsonb
)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_row jsonb;
  v_name text;
  v_parent_name text;
  v_parent_id bigint;
  v_inserted integer := 0;
begin
  if p_enterprise_id is null
     or not exists (select 1 from public.reibi_enterprises where id = p_enterprise_id) then
    raise exception 'enterprise not found';
  end if;
  if jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception 'department rows must be a non-empty array';
  end if;
  if jsonb_array_length(p_rows) > 1000 then
    raise exception 'department import exceeds 1000 rows';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_rows) item
    group by (item->>'level')::integer, lower(btrim(item->>'name'))
    having count(*) > 1
  ) then
    raise exception 'duplicate department name at the same level';
  end if;

  delete from public.reibi_departments where enterprise_id = p_enterprise_id;

  for v_level in 1..4 loop
    for v_row in
      select item
      from jsonb_array_elements(p_rows) item
      where (item->>'level')::integer = v_level
      order by coalesce((item->>'sort_order')::integer, 0), item->>'name'
    loop
      v_name := btrim(v_row->>'name');
      v_parent_name := nullif(btrim(v_row->>'parent_name'), '');
      if v_name is null or v_name = '' then
        raise exception 'department name is required';
      end if;
      if v_level = 1 and v_parent_name is not null then
        raise exception 'level 1 department cannot have a parent';
      elsif v_level > 1 and v_parent_name is null then
        raise exception 'level % department requires a parent', v_level;
      end if;

      v_parent_id := null;
      if v_parent_name is not null then
        select id into v_parent_id
        from public.reibi_departments
        where enterprise_id = p_enterprise_id
          and hierarchy_level = v_level - 1
          and lower(name) = lower(v_parent_name);
        if v_parent_id is null then
          raise exception 'parent department not found: %', v_parent_name;
        end if;
      end if;

      insert into public.reibi_departments (
        enterprise_id, parent_id, name, hierarchy_level, sort_order,
        is_active, source_payload
      ) values (
        p_enterprise_id, v_parent_id, v_name, v_level,
        coalesce((v_row->>'sort_order')::integer, 0), true,
        jsonb_build_object(
          'source', 'department_csv',
          'declared_count', coalesce((v_row->>'declared_count')::integer, 0)
        )
      );
      v_inserted := v_inserted + 1;
    end loop;
  end loop;

  if v_inserted <> jsonb_array_length(p_rows) then
    raise exception 'all department levels must be between 1 and 4';
  end if;
  return v_inserted;
end;
$$;

create or replace function public.reibi_register_announcement(
  p_announcement_id bigint,
  p_profile_id uuid
)
returns public.reibi_announcement_registrations
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_announcement public.reibi_announcements%rowtype;
  v_registration public.reibi_announcement_registrations%rowtype;
  v_registered integer;
begin
  select * into v_announcement
  from public.reibi_announcements
  where id = p_announcement_id
  for update;

  if not found or v_announcement.status <> 'published' then
    raise exception 'announcement is not open for registration';
  end if;

  if not exists (
    select 1
    from public.profiles p
    join public.reibi_enterprises e on e.org_code = p.org_code
    where p.id = p_profile_id and e.id = v_announcement.enterprise_id
  ) then
    raise exception 'profile does not belong to announcement enterprise';
  end if;

  select count(*) into v_registered
  from public.reibi_announcement_registrations
  where announcement_id = p_announcement_id and status = 'registered';

  if v_announcement.quota is not null and v_registered >= v_announcement.quota then
    raise exception 'announcement quota is full';
  end if;

  insert into public.reibi_announcement_registrations (
    announcement_id, profile_id, status, updated_at
  ) values (
    p_announcement_id, p_profile_id, 'registered', now()
  )
  on conflict (announcement_id, profile_id) do update
    set status = 'registered', updated_at = now()
  returning * into v_registration;

  return v_registration;
end;
$$;

alter table public.reibi_announcements enable row level security;
alter table public.reibi_announcement_registrations enable row level security;
alter table public.reibi_access_requests enable row level security;

revoke all privileges on table
  public.reibi_announcements,
  public.reibi_announcement_registrations,
  public.reibi_access_requests
from public, anon, authenticated;

grant all privileges on table
  public.reibi_announcements,
  public.reibi_announcement_registrations,
  public.reibi_access_requests
to service_role;

grant usage, select on all sequences in schema public to service_role;

revoke all on function public.reibi_replace_departments(bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.reibi_replace_departments(bigint, jsonb)
  to service_role;

revoke all on function public.reibi_register_announcement(bigint, uuid)
  from public, anon, authenticated;
grant execute on function public.reibi_register_announcement(bigint, uuid)
  to service_role;
