-- Batch H: one trusted identity registry for SleepM, REIBI L5 and distributors.
-- Authorization remains server-side. Browser roles have no direct access.

alter table public.reibi_internal_users
  drop constraint if exists reibi_internal_users_internal_role_check;

alter table public.reibi_internal_users
  add column profile_id uuid references public.profiles(id) on delete restrict,
  add column org_code text references public.reibi_enterprises(org_code) on update cascade on delete restrict,
  add column department_id bigint references public.reibi_departments(id) on delete restrict,
  add column staff_id bigint references public.reibi_staff(id) on delete set null,
  add column distributor_id bigint references public.reibi_distributors(id) on delete restrict,
  add column permission_overrides jsonb not null default '[]'::jsonb,
  add column invited_at timestamptz,
  add column last_login_at timestamptz,
  add column created_by uuid references public.reibi_internal_users(auth_user_id) on delete set null,
  add column updated_by uuid references public.reibi_internal_users(auth_user_id) on delete set null,
  add constraint reibi_internal_users_role_check check (
    internal_role in (
      'individual', 'member', 'dept_head', 'admin_hr', 'admin_finance',
      'admin_it', 'admin', 'occupational_health', 'reibi_super',
      'reibi_finance', 'reibi_data', 'reibi_cs',
      'partner_primary', 'partner_sub'
    )
  ),
  add constraint reibi_internal_users_profile_scope_check check (
    (
      internal_role in (
        'individual', 'member', 'dept_head', 'admin_hr', 'admin_finance',
        'admin_it', 'admin', 'occupational_health'
      )
      and profile_id is not null
      and profile_id = auth_user_id
    )
    or (
      internal_role not in (
        'individual', 'member', 'dept_head', 'admin_hr', 'admin_finance',
        'admin_it', 'admin', 'occupational_health'
      )
      and profile_id is null
    )
  ),
  add constraint reibi_internal_users_org_scope_check check (
    (
      internal_role in (
        'member', 'dept_head', 'admin_hr', 'admin_finance', 'admin_it',
        'admin', 'occupational_health'
      )
      and org_code is not null
    )
    or (
      internal_role not in (
        'member', 'dept_head', 'admin_hr', 'admin_finance', 'admin_it',
        'admin', 'occupational_health'
      )
      and org_code is null
    )
  ),
  add constraint reibi_internal_users_department_scope_check check (
    (
      internal_role in ('member', 'dept_head', 'admin_hr', 'admin_finance', 'admin_it')
      and department_id is not null
    )
    or (
      internal_role not in ('member', 'dept_head', 'admin_hr', 'admin_finance', 'admin_it')
      and department_id is null
    )
  ),
  add constraint reibi_internal_users_distributor_scope_check check (
    (
      internal_role in ('partner_primary', 'partner_sub')
      and distributor_id is not null
    )
    or (
      internal_role not in ('partner_primary', 'partner_sub')
      and distributor_id is null
    )
  ),
  add constraint reibi_internal_users_permission_overrides_array_check
    check (jsonb_typeof(permission_overrides) = 'array');

create unique index reibi_internal_users_profile_uidx
  on public.reibi_internal_users (profile_id)
  where profile_id is not null;
create unique index reibi_internal_users_distributor_role_uidx
  on public.reibi_internal_users (distributor_id, internal_role)
  where distributor_id is not null;
create index reibi_internal_users_org_role_active_idx
  on public.reibi_internal_users (org_code, internal_role, is_active)
  where org_code is not null;
create index reibi_internal_users_department_idx
  on public.reibi_internal_users (department_id)
  where department_id is not null;
create index reibi_internal_users_staff_idx
  on public.reibi_internal_users (staff_id)
  where staff_id is not null;
create index reibi_internal_users_created_by_idx
  on public.reibi_internal_users (created_by)
  where created_by is not null;
create index reibi_internal_users_updated_by_idx
  on public.reibi_internal_users (updated_by)
  where updated_by is not null;

alter table public.reibi_internal_sessions
  add column revoked_by uuid references public.reibi_internal_users(auth_user_id) on delete set null;

create index reibi_internal_sessions_revoked_by_idx
  on public.reibi_internal_sessions (revoked_by)
  where revoked_by is not null;

create table public.reibi_identity_audit (
  id bigint generated by default as identity primary key,
  actor_auth_user_id uuid references public.reibi_internal_users(auth_user_id) on delete set null,
  target_auth_user_id uuid references public.reibi_internal_users(auth_user_id) on delete set null,
  action text not null check (
    action in ('invite', 'update', 'activate', 'deactivate', 'revoke_sessions', 'login', 'logout')
  ),
  changes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint reibi_identity_audit_changes_object_check
    check (jsonb_typeof(changes) = 'object')
);

create index reibi_identity_audit_target_created_idx
  on public.reibi_identity_audit (target_auth_user_id, created_at desc);
create index reibi_identity_audit_actor_created_idx
  on public.reibi_identity_audit (actor_auth_user_id, created_at desc);
create index reibi_identity_audit_created_idx
  on public.reibi_identity_audit (created_at desc);

create or replace function public.reibi_validate_identity_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_department_org text;
  v_distributor_type text;
begin
  if new.department_id is not null then
    select e.org_code into v_department_org
    from public.reibi_departments d
    join public.reibi_enterprises e on e.id = d.enterprise_id
    where d.id = new.department_id and d.is_active;

    if v_department_org is null or v_department_org <> new.org_code then
      raise exception 'department does not belong to the selected active organization';
    end if;
  end if;

  if new.distributor_id is not null then
    select distributor_type into v_distributor_type
    from public.reibi_distributors
    where id = new.distributor_id and status = 'active';

    if v_distributor_type is null
       or (new.internal_role = 'partner_primary' and v_distributor_type <> 'primary')
       or (new.internal_role = 'partner_sub' and v_distributor_type <> 'sub') then
      raise exception 'distributor type does not match the selected partner role';
    end if;
  end if;

  return new;
end;
$$;

create trigger reibi_internal_users_validate_scope
before insert or update of internal_role, org_code, department_id, distributor_id
on public.reibi_internal_users
for each row execute function public.reibi_validate_identity_scope();

create or replace function public.reibi_touch_identity_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger reibi_internal_users_touch_updated_at
before update on public.reibi_internal_users
for each row execute function public.reibi_touch_identity_updated_at();

alter table public.reibi_identity_audit enable row level security;

revoke all privileges on table public.reibi_identity_audit
from public, anon, authenticated;
grant all privileges on table public.reibi_identity_audit to service_role;

revoke all privileges on sequence public.reibi_identity_audit_id_seq
from public, anon, authenticated;
grant usage, select on sequence public.reibi_identity_audit_id_seq to service_role;

revoke execute on function public.reibi_validate_identity_scope()
from public, anon, authenticated;
grant execute on function public.reibi_validate_identity_scope() to service_role;
revoke execute on function public.reibi_touch_identity_updated_at()
from public, anon, authenticated;
grant execute on function public.reibi_touch_identity_updated_at() to service_role;

comment on table public.reibi_internal_users is
  'Trusted Supabase Auth identity registry and authoritative role/scope binding for SleepM and REIBI.';
comment on table public.reibi_identity_audit is
  'Immutable application-level record of trusted identity and session administration.';
