-- Batch K / L5-01B: concurrency-safe enterprise onboarding.
-- Browser roles intentionally receive no table or function privileges. FastAPI
-- performs authorization and invokes the transaction with service_role.

create sequence public.reibi_onboarding_case_seq;
create sequence public.reibi_enterprise_org_seq;
create sequence public.reibi_credential_letter_seq;

revoke all on sequence public.reibi_onboarding_case_seq from public, anon, authenticated;
revoke all on sequence public.reibi_enterprise_org_seq from public, anon, authenticated;
revoke all on sequence public.reibi_credential_letter_seq from public, anon, authenticated;
grant usage, select on sequence public.reibi_onboarding_case_seq to service_role;
grant usage, select on sequence public.reibi_enterprise_org_seq to service_role;
grant usage, select on sequence public.reibi_credential_letter_seq to service_role;

create table public.reibi_onboarding_cases (
  id bigint generated by default as identity primary key,
  case_no text not null unique,
  credential_no text not null unique,
  enterprise_id bigint not null unique references public.reibi_enterprises(id) on delete restrict,
  status text not null default 'provisioned'
    check (status in ('provisioned', 'handed_off', 'cancelled')),
  admin_email text not null,
  configuration jsonb not null default '{}'::jsonb,
  created_by text not null,
  handed_off_by text,
  handed_off_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index reibi_onboarding_cases_status_created_idx
  on public.reibi_onboarding_cases (status, created_at desc);

alter table public.reibi_onboarding_cases enable row level security;
revoke all on table public.reibi_onboarding_cases from public, anon, authenticated;
grant select, insert, update on table public.reibi_onboarding_cases to service_role;

create or replace function public.reibi_open_enterprise_case(
  p_enterprise jsonb,
  p_sites jsonb,
  p_configuration jsonb,
  p_created_by text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := pg_catalog.clock_timestamp();
  v_alias text;
  v_case_seq bigint;
  v_org_seq bigint;
  v_credential_seq bigint;
  v_case_no text;
  v_org_code text;
  v_credential_no text;
  v_enterprise public.reibi_enterprises%rowtype;
  v_case public.reibi_onboarding_cases%rowtype;
  v_site jsonb;
begin
  if p_enterprise is null or pg_catalog.jsonb_typeof(p_enterprise) <> 'object' then
    raise exception using errcode = '22023', message = 'enterprise payload must be an object';
  end if;
  if pg_catalog.btrim(coalesce(p_enterprise->>'org_name', '')) = '' then
    raise exception using errcode = '23502', message = 'org_name is required';
  end if;
  if pg_catalog.btrim(coalesce(p_enterprise->>'admin_email', '')) = '' then
    raise exception using errcode = '23502', message = 'admin_email is required';
  end if;
  if coalesce((p_enterprise->>'member_limit')::integer, 0) <= 0 then
    raise exception using errcode = '23514', message = 'member_limit must be positive';
  end if;

  v_alias := pg_catalog.upper(pg_catalog.regexp_replace(
    coalesce(nullif(p_enterprise->>'org_alias', ''), pg_catalog.left(p_enterprise->>'org_name', 4)),
    '[^A-Za-z0-9]', '', 'g'
  ));
  v_alias := case
    when pg_catalog.length(v_alias) < 2 then pg_catalog.rpad(v_alias, 2, 'X')
    else pg_catalog.left(v_alias, 4)
  end;
  if v_alias = '' then v_alias := 'XX'; end if;

  v_case_seq := pg_catalog.nextval('public.reibi_onboarding_case_seq'::regclass);
  v_org_seq := pg_catalog.nextval('public.reibi_enterprise_org_seq'::regclass);
  v_credential_seq := pg_catalog.nextval('public.reibi_credential_letter_seq'::regclass);
  v_case_no := 'CASE-' || pg_catalog.to_char(v_now, 'YYMM') || '-' || pg_catalog.lpad(v_case_seq::text, 6, '0');
  v_org_code := 'ORG-' || v_alias || '-' || pg_catalog.to_char(v_now, 'YY') || '-' || pg_catalog.lpad(v_org_seq::text, 6, '0');
  v_credential_no := 'CRED-' || pg_catalog.to_char(v_now, 'YYMM') || '-' || pg_catalog.lpad(v_credential_seq::text, 6, '0');

  insert into public.reibi_enterprises (
    org_code, org_name, org_alias, enterprise_type, status, ubn,
    contact_name, phone, email, address, industry, plan_code,
    member_limit, used_count, contract_start, contract_end, contract_years,
    pay_mode, consultant, partner_code, referral_percent,
    a_layer_fee, b_layer_fee, c_layer_fee, d_layer_fee,
    devices, d_layer_config, source_payload, created_at, updated_at
  ) values (
    v_org_code, pg_catalog.btrim(p_enterprise->>'org_name'), v_alias,
    'enterprise', 'active', nullif(pg_catalog.btrim(p_enterprise->>'ubn'), ''),
    nullif(pg_catalog.btrim(p_enterprise->>'contact_name'), ''),
    nullif(pg_catalog.btrim(p_enterprise->>'phone'), ''),
    pg_catalog.lower(pg_catalog.btrim(p_enterprise->>'admin_email')),
    nullif(pg_catalog.btrim(p_enterprise->>'address'), ''),
    nullif(pg_catalog.btrim(p_enterprise->>'industry'), ''),
    nullif(pg_catalog.btrim(p_enterprise->>'plan_code'), ''),
    (p_enterprise->>'member_limit')::integer, 0,
    nullif(p_enterprise->>'contract_start', '')::date,
    nullif(p_enterprise->>'contract_end', '')::date,
    nullif(p_enterprise->>'contract_years', '')::smallint,
    nullif(pg_catalog.btrim(p_enterprise->>'pay_mode'), ''),
    nullif(pg_catalog.btrim(p_enterprise->>'consultant'), ''),
    nullif(pg_catalog.btrim(p_enterprise->>'partner_code'), ''),
    nullif(p_enterprise->>'referral_percent', '')::numeric,
    coalesce((p_enterprise->>'a_layer_fee')::numeric, 0),
    coalesce((p_enterprise->>'b_layer_fee')::numeric, 0),
    coalesce((p_enterprise->>'c_layer_fee')::numeric, 0),
    coalesce((p_enterprise->>'d_layer_fee')::numeric, 0),
    coalesce(p_enterprise->'devices', '{}'::jsonb),
    coalesce(p_enterprise->'d_layer_config', '{}'::jsonb),
    pg_catalog.jsonb_build_object('onboarding_case_no', v_case_no, 'origin', 'fastapi_l5_01b'),
    v_now, v_now
  ) returning * into v_enterprise;

  if p_sites is not null and pg_catalog.jsonb_typeof(p_sites) = 'array' then
    for v_site in select value from pg_catalog.jsonb_array_elements(p_sites)
    loop
      if pg_catalog.btrim(coalesce(v_site->>'label', '')) <> '' then
        insert into public.reibi_enterprise_sites (
          enterprise_id, artifact_id, label, address, note, sort_order, source_payload, created_at, updated_at
        ) values (
          v_enterprise.id, nullif(v_site->>'artifact_id', ''), pg_catalog.btrim(v_site->>'label'),
          nullif(pg_catalog.btrim(v_site->>'address'), ''), nullif(pg_catalog.btrim(v_site->>'note'), ''),
          coalesce((v_site->>'sort_order')::integer, 0), '{}'::jsonb, v_now, v_now
        );
      end if;
    end loop;
  end if;

  insert into public.reibi_onboarding_cases (
    case_no, credential_no, enterprise_id, status, admin_email,
    configuration, created_by, created_at, updated_at
  ) values (
    v_case_no, v_credential_no, v_enterprise.id, 'provisioned',
    pg_catalog.lower(pg_catalog.btrim(p_enterprise->>'admin_email')),
    coalesce(p_configuration, '{}'::jsonb), p_created_by, v_now, v_now
  ) returning * into v_case;

  return pg_catalog.jsonb_build_object(
    'case', pg_catalog.to_jsonb(v_case),
    'enterprise', pg_catalog.to_jsonb(v_enterprise)
  );
end;
$$;

revoke all on function public.reibi_open_enterprise_case(jsonb, jsonb, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.reibi_open_enterprise_case(jsonb, jsonb, jsonb, text)
  to service_role;
