-- REIBI Batch E: organization analytics, cross-enterprise k-anonymous data,
-- ROI settings and Gemini report snapshots. FastAPI remains the only client.

alter table public.profiles
  add column if not exists research_opt_in boolean not null default false;

create index if not exists profiles_research_org_idx
  on public.profiles (org_code, id)
  where research_opt_in;

create index if not exists sleep_reports_org_created_idx
  on public.sleep_reports (org_code, created_at desc);

create table public.reibi_analytics_settings (
  org_code text primary key references public.organizations(org_code) on delete cascade,
  headcount integer not null default 1000 check (headcount between 1 and 1000000),
  improve_rate numeric(5,2) not null default 60 check (improve_rate between 0 and 100),
  sick_days_reduced numeric(5,2) not null default 2 check (sick_days_reduced between 0 and 365),
  avg_daily_salary numeric(14,2) not null default 3200 check (avg_daily_salary >= 0),
  avg_monthly_salary numeric(14,2) not null default 50000 check (avg_monthly_salary >= 0),
  insurance_saving numeric(14,2) not null default 12000 check (insurance_saving >= 0),
  productivity_gain numeric(5,2) not null default 15 check (productivity_gain between 0 and 100),
  implement_cost numeric(14,2) not null default 6000000 check (implement_cost > 0),
  d_layer_cost numeric(14,2) not null default 90000 check (d_layer_cost >= 0),
  participant_boost numeric(5,2) not null default 12 check (participant_boost between 0 and 100),
  updated_by text,
  updated_at timestamptz not null default now()
);

create table public.reibi_generated_reports (
  id bigint generated by default as identity primary key,
  org_code text references public.organizations(org_code) on delete cascade,
  scope_code text not null,
  report_type text not null check (report_type in (
    'esg', 'okr', 'highrisk', 'kpi', 'roi', 'plan888', 'gri', 'ohs', 'cross_org'
  )),
  title text not null,
  period_start date,
  period_end date,
  department_key text,
  sample_size integer check (sample_size is null or sample_size >= 5),
  metrics_snapshot jsonb not null,
  content text not null,
  ai_provider text not null default 'gemini' check (ai_provider = 'gemini'),
  ai_model text not null,
  generated_by text,
  created_at timestamptz not null default now(),
  check (period_end is null or period_start is null or period_end >= period_start)
);

create index reibi_generated_reports_scope_created_idx
  on public.reibi_generated_reports (scope_code, report_type, created_at desc);
create index reibi_generated_reports_org_created_idx
  on public.reibi_generated_reports (org_code, created_at desc)
  where org_code is not null;

alter table public.reibi_analytics_settings enable row level security;
alter table public.reibi_generated_reports enable row level security;

revoke all on table public.reibi_analytics_settings from anon, authenticated;
revoke all on table public.reibi_generated_reports from anon, authenticated;
revoke all on sequence public.reibi_generated_reports_id_seq from anon, authenticated;
grant all on table public.reibi_analytics_settings to service_role;
grant all on table public.reibi_generated_reports to service_role;
grant usage, select on sequence public.reibi_generated_reports_id_seq to service_role;

create or replace function public.reibi_org_health_snapshot(
  p_org_code text,
  p_period_start date default null,
  p_period_end date default null,
  p_department_key text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_n integer;
  v_result jsonb;
begin
  with eligible as (
    select sr.user_id as profile_id
    from public.sleep_reports sr
    left join public.profiles p on p.id = sr.user_id
    where sr.org_code = p_org_code
      and (p_period_start is null or sr.created_at >= p_period_start::timestamptz)
      and (p_period_end is null or sr.created_at < (p_period_end + 1)::timestamptz)
      and (p_department_key is null or p.department = p_department_key)
    union
    select ha.profile_id
    from public.reibi_health_assessments ha
    left join public.profiles p on p.id = ha.profile_id
    where ha.org_code = p_org_code and ha.profile_id is not null
      and (p_period_start is null or ha.assessed_at >= p_period_start::timestamptz)
      and (p_period_end is null or ha.assessed_at < (p_period_end + 1)::timestamptz)
      and (p_department_key is null or coalesce(ha.department_key, p.department) = p_department_key)
  )
  select count(distinct profile_id) into v_n from eligible;

  if v_n < 5 then
    return jsonb_build_object(
      'sample_size', v_n, 'suppressed', true, 'metrics', null,
      'period_start', p_period_start, 'period_end', p_period_end,
      'department_key', p_department_key
    );
  end if;

  with latest_reports as (
    select distinct on (sr.user_id)
      sr.user_id, sr.sleep_score, sr.sleep_level, sr.pain_score, sr.pain_level,
      sr.work_score, sr.created_at
    from public.sleep_reports sr
    left join public.profiles p on p.id = sr.user_id
    where sr.org_code = p_org_code
      and (p_period_start is null or sr.created_at >= p_period_start::timestamptz)
      and (p_period_end is null or sr.created_at < (p_period_end + 1)::timestamptz)
      and (p_department_key is null or p.department = p_department_key)
    order by sr.user_id, sr.created_at desc
  ),
  latest_assessments as (
    select distinct on (ha.profile_id, ha.assessment_type)
      ha.profile_id, ha.assessment_type, ha.score, ha.level_code, ha.assessed_at
    from public.reibi_health_assessments ha
    left join public.profiles p on p.id = ha.profile_id
    where ha.org_code = p_org_code and ha.profile_id is not null
      and (p_period_start is null or ha.assessed_at >= p_period_start::timestamptz)
      and (p_period_end is null or ha.assessed_at < (p_period_end + 1)::timestamptz)
      and (p_department_key is null or coalesce(ha.department_key, p.department) = p_department_key)
    order by ha.profile_id, ha.assessment_type, ha.assessed_at desc
  )
  select jsonb_build_object(
    'sample_size', v_n,
    'suppressed', false,
    'period_start', p_period_start,
    'period_end', p_period_end,
    'department_key', p_department_key,
    'metrics', jsonb_build_object(
      'sleep', jsonb_build_object(
        'sample_size', (select count(*) from latest_reports where sleep_score is not null),
        'suppressed', (select count(*) < 5 from latest_reports where sleep_score is not null),
        'average_score', (select case when count(*) >= 5 then round(avg(sleep_score), 1) end from latest_reports where sleep_score is not null),
        'green', (select case when count(*) >= 5 then count(*) filter (where sleep_level = 'green') end from latest_reports where sleep_score is not null),
        'yellow', (select case when count(*) >= 5 then count(*) filter (where sleep_level = 'yellow') end from latest_reports where sleep_score is not null),
        'orange', (select case when count(*) >= 5 then count(*) filter (where sleep_level = 'orange') end from latest_reports where sleep_score is not null),
        'red', (select case when count(*) >= 5 then count(*) filter (where sleep_level = 'red') end from latest_reports where sleep_score is not null)
      ),
      'pain', jsonb_build_object(
        'sample_size', (select count(*) from latest_reports where pain_score is not null),
        'suppressed', (select count(*) < 5 from latest_reports where pain_score is not null),
        'average_score', (select case when count(*) >= 5 then round(avg(pain_score), 1) end from latest_reports where pain_score is not null),
        'green', (select case when count(*) >= 5 then count(*) filter (where pain_level = 'green') end from latest_reports where pain_score is not null),
        'yellow', (select case when count(*) >= 5 then count(*) filter (where pain_level = 'yellow') end from latest_reports where pain_score is not null),
        'orange', (select case when count(*) >= 5 then count(*) filter (where pain_level = 'orange') end from latest_reports where pain_score is not null),
        'red', (select case when count(*) >= 5 then count(*) filter (where pain_level = 'red') end from latest_reports where pain_score is not null)
      ),
      'work', jsonb_build_object(
        'sample_size', (select count(*) from latest_reports where work_score is not null),
        'suppressed', (select count(*) < 5 from latest_reports where work_score is not null),
        'average_score', (select case when count(*) >= 5 then round(avg(work_score), 1) end from latest_reports where work_score is not null)
      ),
      'assessments', jsonb_build_object(
        'phq4_sample_size', (select count(*) from latest_assessments where assessment_type = 'phq4'),
        'phq4_average', (select case when count(*) >= 5 then round(avg(score), 1) end from latest_assessments where assessment_type = 'phq4'),
        'pss4_sample_size', (select count(*) from latest_assessments where assessment_type = 'pss4'),
        'pss4_average', (select case when count(*) >= 5 then round(avg(score), 1) end from latest_assessments where assessment_type = 'pss4'),
        'mind3_sample_size', (select count(*) from latest_assessments where assessment_type = 'mind3'),
        'mind3_average', (select case when count(*) >= 5 then round(avg(score), 1) end from latest_assessments where assessment_type = 'mind3'),
        'overwork_count', (select count(*) from latest_assessments where assessment_type = 'ow'),
        'overwork_high_risk', (select case when count(*) >= 5 then count(*) filter (where level_code in ('orange', 'red')) end from latest_assessments where assessment_type = 'ow'),
        'msk_count', (select count(*) from latest_assessments where assessment_type = 'msk'),
        'bsrs5_count', (select count(*) from latest_assessments where assessment_type = 'bsrs5'),
        'bsrs5_high_risk', (select case when count(*) >= 5 then count(*) filter (where level_code in ('orange', 'red')) end from latest_assessments where assessment_type = 'bsrs5')
      )
    )
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.reibi_cross_org_health_snapshot(
  p_period_start date default null,
  p_period_end date default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  with eligible as (
    select sr.org_code, sr.user_id as profile_id
    from public.sleep_reports sr
    join public.profiles p on p.id = sr.user_id and p.research_opt_in
    where sr.org_code is not null
      and (p_period_start is null or sr.created_at >= p_period_start::timestamptz)
      and (p_period_end is null or sr.created_at < (p_period_end + 1)::timestamptz)
    union
    select ha.org_code, ha.profile_id
    from public.reibi_health_assessments ha
    join public.profiles p on p.id = ha.profile_id and p.research_opt_in
    where ha.org_code is not null and ha.profile_id is not null
      and (p_period_start is null or ha.assessed_at >= p_period_start::timestamptz)
      and (p_period_end is null or ha.assessed_at < (p_period_end + 1)::timestamptz)
  ),
  qualified as (
    select org_code, count(distinct profile_id)::integer as sample_size
    from eligible group by org_code having count(distinct profile_id) >= 5
  ),
  latest_reports as (
    select distinct on (sr.org_code, sr.user_id)
      sr.org_code, sr.user_id, sr.sleep_score, sr.sleep_level,
      sr.pain_score, sr.pain_level, sr.work_score
    from public.sleep_reports sr
    join public.profiles p on p.id = sr.user_id and p.research_opt_in
    join qualified q on q.org_code = sr.org_code
    where (p_period_start is null or sr.created_at >= p_period_start::timestamptz)
      and (p_period_end is null or sr.created_at < (p_period_end + 1)::timestamptz)
    order by sr.org_code, sr.user_id, sr.created_at desc
  ),
  stats as (
    select q.org_code, q.sample_size,
      count(lr.user_id)::integer as report_sample_size,
      case when count(lr.sleep_score) >= 5 then round(avg(lr.sleep_score), 1) end as sleep_average,
      case when count(lr.pain_score) >= 5 then round(avg(lr.pain_score), 1) end as pain_average,
      case when count(lr.work_score) >= 5 then round(avg(lr.work_score), 1) end as work_average,
      case when count(lr.sleep_score) >= 5 then count(*) filter (where lr.sleep_level in ('orange', 'red'))::integer end as sleep_high_risk,
      case when count(lr.pain_score) >= 5 then count(*) filter (where lr.pain_level in ('orange', 'red'))::integer end as pain_high_risk
    from qualified q
    left join latest_reports lr on lr.org_code = q.org_code
    group by q.org_code, q.sample_size
  )
  select jsonb_build_object(
    'period_start', p_period_start,
    'period_end', p_period_end,
    'organization_count', count(*),
    'sample_size', coalesce(sum(sample_size), 0),
    'organizations', coalesce(jsonb_agg(jsonb_build_object(
      'org_code', org_code,
      'sample_size', sample_size,
      'report_sample_size', report_sample_size,
      'sleep_average', sleep_average,
      'pain_average', pain_average,
      'work_average', work_average,
      'sleep_high_risk', sleep_high_risk,
      'pain_high_risk', pain_high_risk
    ) order by org_code), '[]'::jsonb)
  ) into v_result
  from stats;

  return v_result;
end;
$$;

revoke all on function public.reibi_org_health_snapshot(text, date, date, text)
  from public, anon, authenticated;
revoke all on function public.reibi_cross_org_health_snapshot(date, date)
  from public, anon, authenticated;
grant execute on function public.reibi_org_health_snapshot(text, date, date, text)
  to service_role;
grant execute on function public.reibi_cross_org_health_snapshot(date, date)
  to service_role;
