-- Batch G: trusted REIBI internal identities, revocable application sessions,
-- and restartable Artifact import metadata. Browser roles intentionally have
-- no access; FastAPI is the only data-plane caller and uses service_role.

create table public.reibi_internal_users (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null,
  internal_role text not null default 'reibi_super'
    check (internal_role in ('reibi_super')),
  is_active boolean not null default true,
  mfa_required boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deactivated_at timestamptz,
  constraint reibi_internal_users_email_lowercase check (email = lower(email)),
  constraint reibi_internal_users_deactivation_consistent
    check ((is_active and deactivated_at is null) or (not is_active))
);

create unique index reibi_internal_users_email_unique
  on public.reibi_internal_users (lower(email));
create index reibi_internal_users_active_idx
  on public.reibi_internal_users (is_active, internal_role);

create table public.reibi_internal_sessions (
  id uuid primary key,
  auth_user_id uuid not null references public.reibi_internal_users(auth_user_id) on delete cascade,
  supabase_session_id uuid,
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_reason text,
  user_agent_hash text,
  ip_hash text,
  constraint reibi_internal_sessions_expiry check (expires_at > issued_at),
  constraint reibi_internal_sessions_revoke_consistent
    check (revoked_at is not null or revoked_reason is null)
);

create index reibi_internal_sessions_user_active_idx
  on public.reibi_internal_sessions (auth_user_id, expires_at desc)
  where revoked_at is null;
create index reibi_internal_sessions_expiry_idx
  on public.reibi_internal_sessions (expires_at)
  where revoked_at is null;

create table public.reibi_internal_login_audit (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  ip_hash text,
  succeeded boolean not null,
  failure_code text,
  auth_user_id uuid references public.reibi_internal_users(auth_user_id) on delete set null,
  created_at timestamptz not null default now(),
  constraint reibi_internal_login_audit_failure_consistent
    check (succeeded or failure_code is not null)
);

create index reibi_internal_login_audit_rate_limit_idx
  on public.reibi_internal_login_audit (email_hash, created_at desc);
create index reibi_internal_login_audit_cleanup_idx
  on public.reibi_internal_login_audit (created_at);

alter table public.reibi_artifact_import_batches
  add column schema_version text,
  add column exported_at timestamptz,
  add column part integer not null default 1 check (part > 0),
  add column parts integer not null default 1 check (parts > 0 and part <= parts),
  add column internal_created_by uuid references public.reibi_internal_users(auth_user_id) on delete set null,
  add column retry_of_batch_id bigint references public.reibi_artifact_import_batches(id) on delete set null,
  add column started_at timestamptz,
  add column last_resumed_at timestamptz,
  add column preflight_summary jsonb not null default '{}'::jsonb;

create unique index reibi_artifact_import_completed_hash_unique
  on public.reibi_artifact_import_batches (source_artifact, export_sha256)
  where status = 'completed' and export_sha256 is not null;
create index reibi_artifact_import_retry_idx
  on public.reibi_artifact_import_batches (retry_of_batch_id)
  where retry_of_batch_id is not null;

alter table public.reibi_internal_users enable row level security;
alter table public.reibi_internal_sessions enable row level security;
alter table public.reibi_internal_login_audit enable row level security;

revoke all privileges on table
  public.reibi_internal_users,
  public.reibi_internal_sessions,
  public.reibi_internal_login_audit
from public, anon, authenticated;

grant all privileges on table
  public.reibi_internal_users,
  public.reibi_internal_sessions,
  public.reibi_internal_login_audit
to service_role;

revoke all privileges on sequence public.reibi_internal_login_audit_id_seq
from public, anon, authenticated;
grant usage, select on sequence public.reibi_internal_login_audit_id_seq to service_role;

comment on table public.reibi_internal_users is
  'Allowlist linking Supabase Auth users to trusted REIBI internal roles.';
comment on table public.reibi_internal_sessions is
  'Revocable, short-lived application sessions for REIBI internal users.';
comment on table public.reibi_internal_login_audit is
  'Hashed-identifier audit trail and rate-limit input; no plaintext password or IP is stored.';
