-- REIBI Batch D: personal health, occupational-health and OHS workflows.
-- Browser roles remain revoked; FastAPI is the authorization boundary.

alter table public.organizations
  add column if not exists occupational_health_pin text,
  add column if not exists oh_roster_visible boolean not null default false;

alter table public.reibi_health_assessments
  drop constraint if exists reibi_health_assessments_assessment_type_check;

alter table public.reibi_health_assessments
  add constraint reibi_health_assessments_assessment_type_check
  check (assessment_type in (
    'combined', 'sleep', 'pain', 'work', 'ow', 'msk', 'bsrs5', 'violence',
    'mental', 'phq4', 'pss4', 'mind3', 'three_highs'
  ));

alter table public.reibi_health_assessments
  add column if not exists department_key text,
  add column if not exists consent_org_aggregate boolean not null default false;

alter table public.reibi_health_diary_entries
  add constraint reibi_health_diary_entries_profile_type_date_key
  unique (profile_id, diary_type, entry_date);

alter table public.reibi_ohs_records
  drop constraint if exists reibi_ohs_records_record_type_check;

alter table public.reibi_ohs_records
  add constraint reibi_ohs_records_record_type_check
  check (record_type in (
    'hazard', 'measure', 'review', 'meta', 'roster', 'schedule', 'tracking', 'interview'
  ));

create table public.reibi_point_ledger (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  org_code text references public.organizations(org_code) on delete set null,
  event_code text not null,
  event_key text not null,
  points integer not null check (points <> 0),
  metadata jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  unique (profile_id, event_key)
);
create index reibi_point_ledger_profile_created_idx
  on public.reibi_point_ledger (profile_id, created_at desc);
create index reibi_point_ledger_org_event_idx
  on public.reibi_point_ledger (org_code, event_code, created_at desc);

create table public.reibi_action_checkins (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  org_code text references public.organizations(org_code) on delete set null,
  action_code text not null,
  action_label text not null,
  checked_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (profile_id, action_code, checked_on)
);
create index reibi_action_checkins_profile_date_idx
  on public.reibi_action_checkins (profile_id, checked_on desc);

create table public.reibi_vital_profiles (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  org_code text references public.organizations(org_code) on delete set null,
  department_key text,
  department_consent boolean not null default false,
  health_status text not null default 'none'
    check (health_status in ('none', 'borderline', 'diagnosed')),
  systolic integer check (systolic is null or systolic between 50 and 300),
  diastolic integer check (diastolic is null or diastolic between 30 and 200),
  fasting_glucose numeric(6,2) check (fasting_glucose is null or fasting_glucose between 20 and 1000),
  ldl numeric(6,2) check (ldl is null or ldl between 0 and 1000),
  height_cm numeric(6,2) check (height_cm is null or height_cm between 50 and 260),
  weight_kg numeric(6,2) check (weight_kg is null or weight_kg between 10 and 500),
  waist_cm numeric(6,2) check (waist_cm is null or waist_cm between 20 and 300),
  source_payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create index reibi_vital_profiles_org_consent_idx
  on public.reibi_vital_profiles (org_code, department_key)
  where department_consent;

create table public.reibi_feedback_surveys (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  org_code text references public.organizations(org_code) on delete set null,
  department_key text,
  period_key text not null check (period_key ~ '^[0-9]{4}-Q[1-4]$'),
  audience_role text not null,
  answers jsonb not null,
  satisfaction_score integer check (satisfaction_score is null or satisfaction_score between 1 and 5),
  nps_score integer check (nps_score is null or nps_score between 0 and 10),
  free_text text,
  created_at timestamptz not null default now(),
  unique (profile_id, period_key)
);
create index reibi_feedback_surveys_org_period_idx
  on public.reibi_feedback_surveys (org_code, period_key);

create table public.reibi_eap_resources (
  id bigint generated by default as identity primary key,
  org_code text references public.organizations(org_code) on delete cascade,
  category_code text not null check (category_code in ('A', 'B', 'C', 'D', 'E')),
  title text not null,
  description text,
  phone text,
  url text,
  is_emergency boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (phone is not null or url is not null or description is not null)
);
create index reibi_eap_resources_scope_idx
  on public.reibi_eap_resources (org_code, category_code, is_active, sort_order);

insert into public.reibi_eap_resources
  (category_code, title, description, phone, is_emergency, sort_order, created_by)
values
  ('A', '安心專線 1925', '24 小時心理支持與危機協助。', '1925', true, 10, 'migration'),
  ('A', '緊急救護 119', '有立即生命危險時請撥打。', '119', true, 20, 'migration'),
  ('B', '心理諮商與身心科資源', '可洽公司 EAP、心理師或身心科／精神科。', null, false, 10, 'migration'),
  ('D', '職場健康諮詢', '可洽臨場健康服務醫師、護理師或健康管理師。', null, false, 10, 'migration');

create index if not exists reibi_payment_schedules_contract_id_idx
  on public.reibi_payment_schedules (contract_id);

alter table public.reibi_point_ledger enable row level security;
alter table public.reibi_action_checkins enable row level security;
alter table public.reibi_vital_profiles enable row level security;
alter table public.reibi_feedback_surveys enable row level security;
alter table public.reibi_eap_resources enable row level security;

revoke all on table public.reibi_point_ledger from anon, authenticated;
revoke all on table public.reibi_action_checkins from anon, authenticated;
revoke all on table public.reibi_vital_profiles from anon, authenticated;
revoke all on table public.reibi_feedback_surveys from anon, authenticated;
revoke all on table public.reibi_eap_resources from anon, authenticated;
grant all on table public.reibi_point_ledger to service_role;
grant all on table public.reibi_action_checkins to service_role;
grant all on table public.reibi_vital_profiles to service_role;
grant all on table public.reibi_feedback_surveys to service_role;
grant all on table public.reibi_eap_resources to service_role;
revoke all on sequence public.reibi_point_ledger_id_seq from anon, authenticated;
revoke all on sequence public.reibi_action_checkins_id_seq from anon, authenticated;
revoke all on sequence public.reibi_feedback_surveys_id_seq from anon, authenticated;
revoke all on sequence public.reibi_eap_resources_id_seq from anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.reibi_point_balance(p_profile_id uuid)
returns integer
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(sum(points), 0)::integer
  from public.reibi_point_ledger
  where profile_id = p_profile_id;
$$;

create or replace function public.reibi_adjust_points(
  p_profile_id uuid,
  p_org_code text,
  p_event_code text,
  p_event_key text,
  p_points integer,
  p_metadata jsonb default '{}'::jsonb,
  p_created_by text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_balance integer;
  v_inserted_count integer := 0;
begin
  if p_points = 0 then
    raise exception 'points must not be zero';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_profile_id::text, 0));
  select public.reibi_point_balance(p_profile_id) into v_balance;
  if p_points < 0 and v_balance + p_points < 0 then
    raise exception 'insufficient points';
  end if;

  insert into public.reibi_point_ledger
    (profile_id, org_code, event_code, event_key, points, metadata, created_by)
  values
    (p_profile_id, p_org_code, p_event_code, p_event_key, p_points,
     coalesce(p_metadata, '{}'::jsonb), p_created_by)
  on conflict (profile_id, event_key) do nothing;
  get diagnostics v_inserted_count = row_count;

  select public.reibi_point_balance(p_profile_id) into v_balance;
  return jsonb_build_object('awarded', v_inserted_count = 1, 'balance', v_balance);
end;
$$;

create or replace function public.reibi_checkin_action(
  p_profile_id uuid,
  p_org_code text,
  p_action_code text,
  p_action_label text,
  p_checked_on date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_balance integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_profile_id::text || ':' || p_action_code, 0));

  if exists (
    select 1 from public.reibi_action_checkins
    where profile_id = p_profile_id
      and action_code = p_action_code
      and checked_on between p_checked_on - 6 and p_checked_on
  ) then
    raise exception 'same action requires a 7-day interval';
  end if;

  insert into public.reibi_action_checkins
    (profile_id, org_code, action_code, action_label, checked_on)
  values (p_profile_id, p_org_code, p_action_code, p_action_label, p_checked_on);

  insert into public.reibi_point_ledger
    (profile_id, org_code, event_code, event_key, points, metadata, created_by)
  values (
    p_profile_id, p_org_code, 'checkin',
    'checkin:' || p_action_code || ':' || p_checked_on::text,
    5, jsonb_build_object('action_code', p_action_code, 'action_label', p_action_label),
    p_profile_id::text
  );

  select public.reibi_point_balance(p_profile_id) into v_balance;
  return jsonb_build_object('awarded', true, 'points', 5, 'balance', v_balance);
end;
$$;

create or replace function public.reibi_three_highs_aggregate(
  p_org_code text,
  p_department_key text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_n integer;
  v_result jsonb;
begin
  select count(*) into v_n
  from public.reibi_vital_profiles
  where org_code = p_org_code
    and department_consent
    and (p_department_key is null or department_key = p_department_key);

  if v_n < 5 then
    return jsonb_build_object('sample_size', v_n, 'suppressed', true, 'metrics', null);
  end if;

  select jsonb_build_object(
    'sample_size', v_n,
    'suppressed', false,
    'metrics', jsonb_build_object(
      'bp_filled', count(*) filter (where systolic is not null and diastolic is not null),
      'bp_controlled', count(*) filter (where systolic < 130 and diastolic < 80),
      'bp_high_risk', count(*) filter (where systolic > 140 or diastolic > 90),
      'glucose_filled', count(*) filter (where fasting_glucose is not null),
      'glucose_controlled', count(*) filter (where fasting_glucose < 100),
      'glucose_high_risk', count(*) filter (where fasting_glucose > 100),
      'ldl_filled', count(*) filter (where ldl is not null),
      'ldl_controlled', count(*) filter (where ldl < 100),
      'bmi_average', round(avg(weight_kg / nullif((height_cm / 100.0) ^ 2, 0)), 1)
    )
  ) into v_result
  from public.reibi_vital_profiles
  where org_code = p_org_code
    and department_consent
    and (p_department_key is null or department_key = p_department_key);

  return v_result;
end;
$$;

create or replace function public.reibi_feedback_aggregate(
  p_org_code text,
  p_period_key text,
  p_department_key text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_n integer;
  v_result jsonb;
begin
  select count(*) into v_n
  from public.reibi_feedback_surveys
  where org_code = p_org_code and period_key = p_period_key
    and (p_department_key is null or department_key = p_department_key);

  if v_n < 5 then
    return jsonb_build_object('sample_size', v_n, 'suppressed', true, 'metrics', null);
  end if;

  select jsonb_build_object(
    'sample_size', v_n,
    'suppressed', false,
    'metrics', jsonb_build_object(
      'average_satisfaction', round(avg(satisfaction_score), 1),
      'average_nps', round(avg(nps_score), 1),
      'nps', round(
        ((count(*) filter (where nps_score >= 9) - count(*) filter (where nps_score <= 6))::numeric
        / nullif(count(*) filter (where nps_score is not null), 0)) * 100
      )
    )
  ) into v_result
  from public.reibi_feedback_surveys
  where org_code = p_org_code and period_key = p_period_key
    and (p_department_key is null or department_key = p_department_key);

  return v_result;
end;
$$;

revoke all on function public.reibi_point_balance(uuid) from public, anon, authenticated;
revoke all on function public.reibi_adjust_points(uuid, text, text, text, integer, jsonb, text) from public, anon, authenticated;
revoke all on function public.reibi_checkin_action(uuid, text, text, text, date) from public, anon, authenticated;
revoke all on function public.reibi_three_highs_aggregate(text, text) from public, anon, authenticated;
revoke all on function public.reibi_feedback_aggregate(text, text, text) from public, anon, authenticated;
grant execute on function public.reibi_point_balance(uuid) to service_role;
grant execute on function public.reibi_adjust_points(uuid, text, text, text, integer, jsonb, text) to service_role;
grant execute on function public.reibi_checkin_action(uuid, text, text, text, date) to service_role;
grant execute on function public.reibi_three_highs_aggregate(text, text) to service_role;
grant execute on function public.reibi_feedback_aggregate(text, text, text) to service_role;
