-- REIBI 自有體驗場域（移植自 Artifact 主平台的 VenueScreen）。
--
-- 為什麼不能沿用 reibi_enterprise_sites：那張表是 `enterprise_id not null`，
-- 代表**客戶自己的**廠區與辦公室，用於 D 層施工場域與企業內預約。
-- 體驗中心是 REIBI 自己的據點，不屬於任何企業，塞進那張表會讓租戶範圍失去意義。
--
-- ⚠️ 本次僅建立結構，內容為**明確標示的佔位資料**，正式資料待業務端提供。
-- `is_placeholder` 為 true 的場域在前端會顯示警示，且不可被預約 ——
-- 編造的地址如果上線，會有人真的照著跑一趟。

create table if not exists public.reibi_experience_venues (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  city text not null,
  name text not null,
  address text,
  area text,
  -- 交通方式可多條，維持 Artifact 的陣列結構。
  transport jsonb not null default '[]'::jsonb,
  opening_hours text,
  services jsonb not null default '[]'::jsonb,
  note text,
  -- 是否開放「首次免費體驗」。Artifact 的規則是每人限一次。
  first_visit_free boolean not null default false,
  is_placeholder boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.reibi_experience_venues is
  'REIBI 自有體驗中心。與 reibi_enterprise_sites（客戶自有場域）是不同概念，不可混用。';
comment on column public.reibi_experience_venues.is_placeholder is
  '佔位資料旗標。true 代表內容尚未由業務端確認，前端顯示警示且不開放預約。';
comment on column public.reibi_experience_venues.first_visit_free is
  '是否開放首次免費體驗。額度規則為每人一次，由 reibi_venue_free_visits 記錄。';

-- 首次免費體驗的使用紀錄。用獨立表而不是在 appointments 上加旗標：
-- 「這個人用掉免費額度了沒」是一個需要唯一性保證的事實，
-- 放在 appointments 上要靠查詢聚合，兩個並發請求可以同時通過檢查。
create table if not exists public.reibi_venue_free_visits (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  venue_id bigint not null references public.reibi_experience_venues(id) on delete cascade,
  appointment_id uuid references public.appointments(id) on delete set null,
  claimed_at timestamptz not null default now(),
  -- 每人限一次，與場域無關：主鍵只有 profile_id。
  -- 此範圍於 2026-08-20 經業務端確認。若日後改為「每人每場域一次」，
  -- 主鍵改成 (profile_id, venue_id) 即可 —— 那是一個資料庫層級的規則變更，
  -- 不是散落在應用程式各處的 if。
  primary key (profile_id)
);

comment on table public.reibi_venue_free_visits is
  '首次免費體驗額度使用紀錄。主鍵僅 profile_id，因此每人終身一次；'
  '改為每場域一次只需將主鍵改為 (profile_id, venue_id)。';

create index if not exists reibi_experience_venues_active_idx
  on public.reibi_experience_venues (is_active, sort_order)
  where is_active;

alter table public.reibi_experience_venues enable row level security;
alter table public.reibi_venue_free_visits enable row level security;

revoke all on public.reibi_experience_venues from anon, authenticated;
revoke all on public.reibi_venue_free_visits from anon, authenticated;
grant all on public.reibi_experience_venues to service_role;
grant all on public.reibi_venue_free_visits to service_role;

-- 預約指向體驗場域。既有的 service_site_id 指向企業自有場域，兩者並存不衝突。
alter table public.appointments
  add column if not exists experience_venue_id bigint
    references public.reibi_experience_venues(id) on delete set null;

comment on column public.appointments.experience_venue_id is
  'REIBI 體驗中心預約。與 service_site_id（企業自有場域）互斥使用。';

create index if not exists appointments_experience_venue_id_idx
  on public.appointments (experience_venue_id)
  where experience_venue_id is not null;

-- 佔位資料。名稱與地址刻意寫成一望即知的樣板，不使用任何看起來像真的的地址。
insert into public.reibi_experience_venues
  (slug, city, name, address, area, transport, opening_hours, services, note,
   first_visit_free, is_placeholder, sort_order)
values
  ('placeholder-1', '（待填）', '【範例】體驗中心一', '（地址待業務端提供）', '（待填）',
   '["（交通方式待填，可多條）"]'::jsonb, '（開放時間待填）',
   '["舒曼波體驗", "LA200 光能體驗", "自律神經量測"]'::jsonb,
   '這是佔位資料，尚未由業務端確認，因此不開放預約。', false, true, 1),
  ('placeholder-2', '（待填）', '【範例】體驗中心二', '（地址待業務端提供）', '（待填）',
   '["（交通方式待填，可多條）"]'::jsonb, '（開放時間待填）',
   '["舒曼波體驗", "LA200 光能體驗"]'::jsonb,
   '這是佔位資料，尚未由業務端確認，因此不開放預約。', false, true, 2)
on conflict (slug) do nothing;
